name: AWS S3 Sync
description: A Buildkite plugin syncs files to the AWS Simple Storage Service (S3)
author: https://github.com/envato
requirements:
  - aws
configuration:
  properties:
    source:
      type: string
    destination:
      type: string
    delete:
      type: boolean
    follow-symlinks:
      type: boolean
    cache-control:
      type: string
    endpoint-url:
      type: string
  required:
    - source
    - destination
